// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=../../mocks/mock_storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/stepkareserva/obsermon/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockGaugeStorage is a mock of GaugeStorage interface.
type MockGaugeStorage struct {
	ctrl     *gomock.Controller
	recorder *MockGaugeStorageMockRecorder
	isgomock struct{}
}

// MockGaugeStorageMockRecorder is the mock recorder for MockGaugeStorage.
type MockGaugeStorageMockRecorder struct {
	mock *MockGaugeStorage
}

// NewMockGaugeStorage creates a new mock instance.
func NewMockGaugeStorage(ctrl *gomock.Controller) *MockGaugeStorage {
	mock := &MockGaugeStorage{ctrl: ctrl}
	mock.recorder = &MockGaugeStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGaugeStorage) EXPECT() *MockGaugeStorageMockRecorder {
	return m.recorder
}

// FindGauge mocks base method.
func (m *MockGaugeStorage) FindGauge(ctx context.Context, name string) (*models.Gauge, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGauge", ctx, name)
	ret0, _ := ret[0].(*models.Gauge)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindGauge indicates an expected call of FindGauge.
func (mr *MockGaugeStorageMockRecorder) FindGauge(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGauge", reflect.TypeOf((*MockGaugeStorage)(nil).FindGauge), ctx, name)
}

// ListGauges mocks base method.
func (m *MockGaugeStorage) ListGauges(ctx context.Context) (models.GaugesList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGauges", ctx)
	ret0, _ := ret[0].(models.GaugesList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGauges indicates an expected call of ListGauges.
func (mr *MockGaugeStorageMockRecorder) ListGauges(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGauges", reflect.TypeOf((*MockGaugeStorage)(nil).ListGauges), ctx)
}

// ReplaceGauges mocks base method.
func (m *MockGaugeStorage) ReplaceGauges(ctx context.Context, val models.GaugesList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceGauges", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceGauges indicates an expected call of ReplaceGauges.
func (mr *MockGaugeStorageMockRecorder) ReplaceGauges(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceGauges", reflect.TypeOf((*MockGaugeStorage)(nil).ReplaceGauges), ctx, val)
}

// SetGauge mocks base method.
func (m *MockGaugeStorage) SetGauge(ctx context.Context, val models.Gauge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockGaugeStorageMockRecorder) SetGauge(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockGaugeStorage)(nil).SetGauge), ctx, val)
}

// SetGauges mocks base method.
func (m *MockGaugeStorage) SetGauges(ctx context.Context, val models.GaugesList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauges", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGauges indicates an expected call of SetGauges.
func (mr *MockGaugeStorageMockRecorder) SetGauges(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauges", reflect.TypeOf((*MockGaugeStorage)(nil).SetGauges), ctx, val)
}

// MockCounterStorage is a mock of CounterStorage interface.
type MockCounterStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCounterStorageMockRecorder
	isgomock struct{}
}

// MockCounterStorageMockRecorder is the mock recorder for MockCounterStorage.
type MockCounterStorageMockRecorder struct {
	mock *MockCounterStorage
}

// NewMockCounterStorage creates a new mock instance.
func NewMockCounterStorage(ctrl *gomock.Controller) *MockCounterStorage {
	mock := &MockCounterStorage{ctrl: ctrl}
	mock.recorder = &MockCounterStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterStorage) EXPECT() *MockCounterStorageMockRecorder {
	return m.recorder
}

// FindCounter mocks base method.
func (m *MockCounterStorage) FindCounter(ctx context.Context, name string) (*models.Counter, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCounter", ctx, name)
	ret0, _ := ret[0].(*models.Counter)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindCounter indicates an expected call of FindCounter.
func (mr *MockCounterStorageMockRecorder) FindCounter(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCounter", reflect.TypeOf((*MockCounterStorage)(nil).FindCounter), ctx, name)
}

// ListCounters mocks base method.
func (m *MockCounterStorage) ListCounters(ctx context.Context) (models.CountersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCounters", ctx)
	ret0, _ := ret[0].(models.CountersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCounters indicates an expected call of ListCounters.
func (mr *MockCounterStorageMockRecorder) ListCounters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCounters", reflect.TypeOf((*MockCounterStorage)(nil).ListCounters), ctx)
}

// ReplaceCounters mocks base method.
func (m *MockCounterStorage) ReplaceCounters(ctx context.Context, val models.CountersList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceCounters", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceCounters indicates an expected call of ReplaceCounters.
func (mr *MockCounterStorageMockRecorder) ReplaceCounters(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceCounters", reflect.TypeOf((*MockCounterStorage)(nil).ReplaceCounters), ctx, val)
}

// UpdateCounter mocks base method.
func (m *MockCounterStorage) UpdateCounter(ctx context.Context, val models.Counter) (*models.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", ctx, val)
	ret0, _ := ret[0].(*models.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockCounterStorageMockRecorder) UpdateCounter(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockCounterStorage)(nil).UpdateCounter), ctx, val)
}

// UpdateCounters mocks base method.
func (m *MockCounterStorage) UpdateCounters(ctx context.Context, vals models.CountersList) (models.CountersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounters", ctx, vals)
	ret0, _ := ret[0].(models.CountersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCounters indicates an expected call of UpdateCounters.
func (mr *MockCounterStorageMockRecorder) UpdateCounters(ctx, vals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounters", reflect.TypeOf((*MockCounterStorage)(nil).UpdateCounters), ctx, vals)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// FindCounter mocks base method.
func (m *MockStorage) FindCounter(ctx context.Context, name string) (*models.Counter, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCounter", ctx, name)
	ret0, _ := ret[0].(*models.Counter)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindCounter indicates an expected call of FindCounter.
func (mr *MockStorageMockRecorder) FindCounter(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCounter", reflect.TypeOf((*MockStorage)(nil).FindCounter), ctx, name)
}

// FindGauge mocks base method.
func (m *MockStorage) FindGauge(ctx context.Context, name string) (*models.Gauge, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGauge", ctx, name)
	ret0, _ := ret[0].(*models.Gauge)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindGauge indicates an expected call of FindGauge.
func (mr *MockStorageMockRecorder) FindGauge(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGauge", reflect.TypeOf((*MockStorage)(nil).FindGauge), ctx, name)
}

// ListCounters mocks base method.
func (m *MockStorage) ListCounters(ctx context.Context) (models.CountersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCounters", ctx)
	ret0, _ := ret[0].(models.CountersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCounters indicates an expected call of ListCounters.
func (mr *MockStorageMockRecorder) ListCounters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCounters", reflect.TypeOf((*MockStorage)(nil).ListCounters), ctx)
}

// ListGauges mocks base method.
func (m *MockStorage) ListGauges(ctx context.Context) (models.GaugesList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGauges", ctx)
	ret0, _ := ret[0].(models.GaugesList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGauges indicates an expected call of ListGauges.
func (mr *MockStorageMockRecorder) ListGauges(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGauges", reflect.TypeOf((*MockStorage)(nil).ListGauges), ctx)
}

// ReplaceCounters mocks base method.
func (m *MockStorage) ReplaceCounters(ctx context.Context, val models.CountersList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceCounters", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceCounters indicates an expected call of ReplaceCounters.
func (mr *MockStorageMockRecorder) ReplaceCounters(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceCounters", reflect.TypeOf((*MockStorage)(nil).ReplaceCounters), ctx, val)
}

// ReplaceGauges mocks base method.
func (m *MockStorage) ReplaceGauges(ctx context.Context, val models.GaugesList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceGauges", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceGauges indicates an expected call of ReplaceGauges.
func (mr *MockStorageMockRecorder) ReplaceGauges(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceGauges", reflect.TypeOf((*MockStorage)(nil).ReplaceGauges), ctx, val)
}

// SetGauge mocks base method.
func (m *MockStorage) SetGauge(ctx context.Context, val models.Gauge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockStorageMockRecorder) SetGauge(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockStorage)(nil).SetGauge), ctx, val)
}

// SetGauges mocks base method.
func (m *MockStorage) SetGauges(ctx context.Context, val models.GaugesList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauges", ctx, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGauges indicates an expected call of SetGauges.
func (mr *MockStorageMockRecorder) SetGauges(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauges", reflect.TypeOf((*MockStorage)(nil).SetGauges), ctx, val)
}

// UpdateCounter mocks base method.
func (m *MockStorage) UpdateCounter(ctx context.Context, val models.Counter) (*models.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", ctx, val)
	ret0, _ := ret[0].(*models.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockStorageMockRecorder) UpdateCounter(ctx, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockStorage)(nil).UpdateCounter), ctx, val)
}

// UpdateCounters mocks base method.
func (m *MockStorage) UpdateCounters(ctx context.Context, vals models.CountersList) (models.CountersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounters", ctx, vals)
	ret0, _ := ret[0].(models.CountersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCounters indicates an expected call of UpdateCounters.
func (mr *MockStorageMockRecorder) UpdateCounters(ctx, vals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounters", reflect.TypeOf((*MockStorage)(nil).UpdateCounters), ctx, vals)
}
